action_id: trunk-upgrade-available
date: 2025-08-09 22:21:15
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1754778075
full_timestamp:
  nanos: 181205000
  seconds: 1754778075
trunk_version: 1.24.0
